export const menuItems = [
  {
    id: "1",
    name: "Classic Burger",
    price: 12.99,
    image: "/images/blueberry.png",
    images: ["/images/blueberry.png", "/images/landing.jpg", "/images/cozy-place.jpg"],
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    category: "burgers",
  },
  {
    id: "2",
    name: "Margherita Pizza",
    price: 14.99,
    image: "/images/landing.jpg",
    images: ["/images/landing.jpg", "/images/cozy-place.jpg", "/images/blueberry.png"],
    description: "Fresh tomatoes, mozzarella, basil, and olive oil",
    category: "pizza",
  },
  {
    id: "3",
    name: "Caesar Salad",
    price: 8.99,
    image: "/images/cozy-place.jpg",
    images: ["/images/cozy-place.jpg", "/images/blueberry.png", "/images/landing.jpg"],
    description: "Crisp romaine lettuce, croutons, parmesan, and caesar dressing",
    category: "salads",
  },
  {
    id: "4",
    name: "Buffalo Wings",
    price: 10.99,
    image: "/images/relax-atmosphere.jpg",
    images: ["/images/relax-atmosphere.jpg", "/images/landing.jpg", "/images/cozy-place.jpg"],
    description: "Crispy wings with spicy buffalo sauce",
    category: "appetizers",
  },
  {
    id: "5",
    name: "BBQ Ribs",
    price: 18.99,
    image: "/images/landing.jpg",
    images: ["/images/landing.jpg", "/images/blueberry.png", "/images/cozy-place.jpg"],
    description: "Tender pork ribs with sweet and tangy BBQ sauce",
    category: "mains",
  },
  {
    id: "6",
    name: "Vegetarian Pasta",
    price: 13.99,
    image: "/images/cozy-place.jpg",
    images: ["/images/cozy-place.jpg", "/images/landing.jpg", "/images/blueberry.png"],
    description: "Fresh pasta with seasonal vegetables and pesto sauce",
    category: "pasta",
  },
  {
    id: "7",
    name: "Seafood Paella",
    price: 24.99,
    image: "/images/blueberry.png",
    images: ["/images/blueberry.png", "/images/cozy-place.jpg", "/images/landing.jpg"],
    description: "Spanish rice dish with mixed seafood and saffron",
    category: "mains",
  },
  {
    id: "8",
    name: "Greek Salad",
    price: 9.99,
    image: "/images/landing.jpg",
    images: ["/images/landing.jpg", "/images/blueberry.png", "/images/cozy-place.jpg"],
    description: "Fresh vegetables, olives, and feta cheese with olive oil dressing",
    category: "salads",
  },
  {
    id: "9",
    name: "Pepperoni Pizza",
    price: 15.99,
    image: "/images/cozy-place.jpg",
    images: ["/images/cozy-place.jpg", "/images/landing.jpg", "/images/blueberry.png"],
    description: "Classic pizza with pepperoni, mozzarella, and tomato sauce",
    category: "pizza",
  }
];
